namespace Rudi.Dev.FastEndpoints.TsClientGenerator.Configuration;

public class ApiClientOptions
{
    /// <summary>
    /// The default URL that the API Client will use, WITHOUT the trailing slash
    /// </summary>
    public string BaseUrl { get; set; } = "https://localhost:7000";

    /// <summary>
    /// The name of the generated client
    /// </summary>
    public string ClassName { get; set; } = "ClientApi";
    
    public bool ExportInstance { get; set; }

    /// <summary>
    /// The name of the base class that the API Client extends
    /// </summary>
    public string? Extends { get; set; }

    /// <summary>
    /// The import path for <see cref="Extends"/> on the client
    /// </summary>
    public string? ExtendsImportPath { get; set; }

    /// <summary>
    /// From the base class, define a method that modifies the RequestInit object
    /// </summary>
    /// <example>
    /// ExtendsRequestInitMethod = "addHeaders";
    /// 
    /// async addHeaders(fetchOpts: RequestInit): Promise&lt;RequestInit&gt; {
    ///     fetchOpts.headers = {
    ///         ...fetchOpts.headers,
    ///         Authorization: "Bearer 12345",
    ///     };
    ///     return fetchOpts;
    /// }
    /// </example>
    public string? ExtendsRequestInitMethod { get; set; }

    /// <summary>
    /// From the base class, define a method that gets the base URL
    /// </summary>
    public string? ExtendsBaseUrlMethod { get; set; }

    /// <summary>
    /// Prepend a header to the generated file
    /// </summary>
    public string? FileHeader { get; set; } = """
//-------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool (Rudi.Dev.FastEndpoints.TsClientGenerator).
//
//     Changes to this file will be lost when the code is regenerated. If you need to
//     modify behaviour, use a base class or override templates for generation.
// </auto-generated>
//-------------------------------------------------------------------------------------
""";
}